const express = require("express");
const app = express();

app.use(express.json());

/**
 * 🟢 SIMPLE API
 */
app.get("/hallo", (req, res) => {
  res.json({
    type: "custom-api",
    message: "hallo hallo 👋",
    comment: "This is your own API endpoint"
  });
});

/**
 * 🤖 GPT API
 */
app.get("/gpt", async (req, res) => {
  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "user", content: "hallo" }
        ]
      })
    });

    const data = await response.json();

    // safety check (prevents crash)
    if (!data.choices || !data.choices[0]) {
      return res.status(500).json({
        error: "GPT failed",
        raw: data
      });
    }

    const answer = data.choices[0].message.content;

    res.json({
      type: "gpt-api",
      input: "hallo",
      reply: answer,
      comment: "Response generated by OpenAI GPT via server-side API"
    });

  } catch (err) {
    res.status(500).json({
      error: "Server error",
      message: err.message
    });
  }
});

/**
 * 🚀 START SERVER (IMPORTANT FOR CLOUD RUN)
 */
const port = process.env.PORT || 8080;
app.listen(port, () => {
  console.log("Server running on port", port);
});
